### ISSUE TITLE
Building Using Microsoft Visual Studio

### ISSUE THREAD

**Issue by udgover** [libyal/libbfio#1]
The provided sln file is wrong concerning libcfile because libcfile_stream.c is no longer existing. Removing it from the libcfile tree project leads to a successful compilation.

Moreover, before being able to compile from VS, it's needed to ./configure in order to generate types.h and config.h which is not very practical when dealing with automated builds... What could be the workaround here?

**Comment by joachimmetz** [comment]
> What could be the workaround here?

https://github.com/libyal/libbfio/blob/master/autogen.ps1

**Comment by joachimmetz** [comment]
> The provided sln file is wrong concerning libcfile because libcfile_stream.c is no longer existing. 

I'll have a look. Know you can regenerate them from the automake/autoconf files with this script: https://github.com/libyal/libyal/wiki/msvscpp-convert

**Comment by udgover** [comment]
Thanks! I was not aware of msvscpp-convert. You may add a reference in the building instructions on the wiki.

**Comment by joachimmetz** [comment]
I've added a reminder to add a mention of libyal vstools to the project wiki to https://github.com/libyal/libyal/issues/32. Closing this issue.
