### ISSUE TITLE
test_library.sh fails on some architectures

### ISSUE THREAD

**Issue by hillu** [libyal/libbfio#2]
libbfio can't be built on all architectures, see: https://buildd.debian.org/status/package.php?p=libbfio

    bfio_test_handle.c:803 result (1) != -1

**Comment by joachimmetz** [comment]
I'll have a look when time permits

**Comment by joachimmetz** [comment]
The test that fails is initialize with a failing memset:
https://github.com/libyal/libbfio/blob/master/tests/bfio_test_handle.c#L771

Anything that makes these architectures different? In terms of memset optimization?

Otherwise I could try to detect these architectures and skip this specific test on those. Seeing that, to my knowledge, there is not a really nice way to test this error case.

**Comment by hillu** [comment]
* Joachim Metz:

> The test that fails is initialize with a failing memset:
> https://github.com/libyal/libbfio/blob/master/tests/bfio_test_handle.c#L771
>
> Anything that makes these architectures different?

I don't know yet, haven't even looked at the test with a debugger. Will
do that over the weekend as time permits.

Cheers,
-Hilko

**Comment by joachimmetz** [comment]
This might be one of these test where a debugger is not useful.

memset can be optimized out by the compiler as a function, so technically the test is testing against a function that does not exists, so the error condition cannot be triggered. If I have some way of detecting these platform/compiler behaviour I can just skip the test for those platforms. 

The test is primarily there to test the error path when memset is compiled as function.

**Comment by hillu** [comment]
Alright, so I solved it by adding an architecture `#ifdef`. See http://sources.debian.net/src/libbfio/20170123-3/debian/patches/0002-Don-t-define-HAVE_BFIO_TEST_MEMORY-on-some-architect.patch/

**Comment by joachimmetz** [comment]
thanks, I'll have a look at adding this to the tests

**Comment by joachimmetz** [comment]
https://github.com/libyal/libbfio/commit/b3596d9cf6762cda25e2dbf539a81d941ce79270 should fix it
