### ISSUE TITLE
MacOS: clang complaining about implicit declaration of function 'memory_free'

### ISSUE THREAD

**Issue by SeaQuench** [libyal/libbfio#5]
Admitting that no error results when building this library on Ubuntu; nevertheless, the following error is produced when kicking off a build for a modern MacOS (12) via pip: `pip install libesedb-python`
```
libbfio/libbfio_file.c:273:3: error: implicit declaration of function 'memory_free' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
```
Line 273 of the stated file indeed contains a call to memory_free(), and we see several definitions for this function in the included header file, `memory.h`; however, none of these definitions appear to be valid for the macOS using clang. 

```
/* Memory free
 */
#if defined( HAVE_GLIB_H )
#define memory_free( buffer ) \
  g_free( (gpointer) buffer )

#elif defined( WINAPI )
#define memory_free( buffer ) \
  ( buffer == NULL ) ? TRUE : HeapFree( GetProcessHeap(), 0, (LPVOID) buffer )

#elif defined( HAVE_FREE )
#define memory_free( buffer ) \
  free( (void *) buffer )
#endif
```

**Comment by joachimmetz** [comment]
CI MacOS clang build is working fine: https://ci.appveyor.com/project/libyal/libbfio/build/job/yv3y3q4ipqw9okv3 can you provide more information about your configuration and attach config.log

**Comment by SeaQuench** [comment]
My coworkers have determined that this error occurs with clang on Monterrey but not on Ventura. 
Fails: `Target: x86_64-apple-darwin21.6.0 Apple clang version 13.1.6 (clang-1316.0.21.2.5)`
Succeeds: `Target: x86_64-apple-darwin22.2.0 Apple clang version 13.0.0 (clang-1300.0.29.3)`

How would you have me obtain the config.log? I don't know my way around clang very well.

**Comment by joachimmetz** [comment]
> My coworkers have determined that this error occurs with clang on Monterrey but not on Ventura.

CI test run on Monterey, first check if your xcode installation is installed correctly

> How would you have me obtain the config.log? I don't know my way around clang very well.

config.log is generated by `./configure` not by clang, should be in the build directory.

**Comment by SeaQuench** [comment]
Upgraded xcode to 14.2 and was able to rebuild library without issue.
